---
insertion: -2
deletion: -2
substitution: 
  A-G: -1
  A-C: -1
  A-T: -1
  A-A: 1
  T-A: -1
  T-C: -1
  T-G: -1
  T-T: 1
  C-A: -1
  C-G: -1
  C-T: -1
  C-C: 1
  G-A: -1
  G-C: -1
  G-T: -1
  G-G: 1
s1: 'AGGCTG'
s2: 'ACGCTTG'
